### ISSUE TITLE
Running locally with cog on a M1 chip

### ISSUE THREAD

**Issue by gibranpulga** [replicate/dreambooth#21]
Hey everyone ! 
I'm trying to run locally with cog, but when trying to download the weights from hugging face (cog run script/download-weights) I'm getting this error:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ⅹ Docker is missing required device driver

```

I'm on a M1 macbook and couldn't find on the docs if this command should be run differently, any ideas?

**Comment by gibranpulga** [comment]
Update: I was able to run it, by setting "gpu" to false on cog.yaml (this was not on any docs).
Now when trying to train the model (running  cog predict) I'm getting this other issue:

`/bin/sh: 1: nvidia-smi: not found
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 650, in startup
    handler()
  File "/usr/local/lib/python3.10/site-packages/cog/server/http.py", line 40, in startup
    predictor.setup()
  File "/src/predictor.py", line 29, in setup
    check_call("nvidia-smi", shell=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'nvidia-smi' returned non-zero exit status 127.

ERROR:    Application startup failed. Exiting.
ⅹ Failed to get container status: exit status 1`

**Comment by zeke-john** [comment]
any update
