### ISSUE TITLE
nvidia-smi returns a non zero error.

### ISSUE THREAD

**Issue by ASparkOfFire** [replicate/dreambooth#30]
I'm trying to run this using Cog on an Ubuntu 18.04 LTS Virtual Machine having RTX 6000 passed through'ed to it. But I'm facing the below error.

```
INFO:     Started server process [7]
INFO:     Waiting for application startup.
/bin/sh: 1: nvidia-smi: not found
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/cog/server/worker.py", line 178, in _setup
self._predictor.setup()
File "/src/predictor.py", line 29, in setup
check_call("nvidia-smi", shell=True)
File "/root/.pyenv/versions/3.10.11/lib/python3.10/subprocess.py", line 369, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'nvidia-smi' returned non-zero exit status 127.
ERROR:    Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/starlette/routing.py", line 656, in startup
    handler()
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/cog/server/http.py", line 60, in startup
    runner.setup()
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/cog/server/runner.py", line 22, in setup
    for event in self._worker.setup():
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/cog/server/worker.py", line 126, in _wait
    raise FatalWorkerException(raise_on_error)
cog.server.exceptions.FatalWorkerException: Predictor errored during setup

ERROR:    Application startup failed. Exiting.

```

The container image seems to be lacking "nvidia-smi" because of which Pytorch cannot determine whether CUDA is available or not.

**Comment by ASparkOfFire** [comment]
Stupid issue at my end: I didn't specify --gpus argument to docker while running the container.
