### ISSUE TITLE
validate training data and respond with errors before running inference code

### ISSUE THREAD

**Issue by zeke** [replicate/dreambooth#5]
Using this code:

```py
model = replicate.models.get("replicate/cog-dreambooth-trainer")
version = model.versions.get("b9a7267b10bb9e5fb19eca853ee9582e8838c8cfe1bf174f4cd50991c857992e")
output = version.predict(instance_data=open("data.zip", "rb"))
```

The prediction runs for a few minutes, then fails with this error:

```
Traceback (most recent call last):
  File "/Users/z/git/replicate/cog-dreambooth/train.py", line 39, in <module>
    train()
  File "/Users/z/git/replicate/cog-dreambooth/train.py", line 32, in train
    output = version.predict(instance_data=open("data.zip", "rb"))
  File "/Users/z/.pyenv/versions/python-3.10.4/lib/python3.10/site-packages/replicate/version.py", line 31, in predict
    raise ModelError(prediction.error)
replicate.exceptions.ModelError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>
```

cc @chenxwh @bfirsh

**Comment by chenxwh** [comment]
This is solved by making sure that training images should put under `/data` before zipping if it is not using the [github.com/replicate/dreambooth-template](https://github.com/replicate/dreambooth-template) flow. Noted in README [here](https://replicate.com/replicate/dreambooth) too.
