### ISSUE TITLE
Can't load the model for 'stabilityai/sd-vae-ft-mse'.

### ISSUE THREAD

**Issue by zeke** [replicate/dreambooth#8]
Running this command on a GPU codespace:

```
$ cog predict -i instance_prompt="a photo of zzz" -i class_prompt="a photo of a man" -i instance_data=@instance_data.zip
```

I get this error:

```
  File "/root/.pyenv/versions/3.10.8/lib/python3.10/site-packages/diffusers/modeling_utils.py", line 439, in from_pretrained
    raise EnvironmentError(
OSError: Can't load the model for 'stabilityai/sd-vae-ft-mse'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'stabilityai/sd-vae-ft-mse' is the correct path to a directory containing a file named diffusion_pytorch_model.bin
ⅹ /predictions call returned status 500
```

cc @chenxwh

**Comment by zeke** [comment]
Turns out you need to run the download script first.

> The default stable diffusion model used is `runwayml/stable-diffusion-v1-5` (fp16), and `stabilityai/sd-vae-ft-mse` as `pretrained_vae`, . If you like to work with the flow locally, run `download.py` first to prepare the weight files that is later used for training.

https://github.com/replicate/dreambooth/blob/215cb3bea48eddee9a4823bdb1aed1518db112a3/README.md#note

**Comment by zeke** [comment]
```
python download.py

Traceback (most recent call last):
  File "/workspaces/dreambooth/download.py", line 3, in <module>
    from diffusers import StableDiffusionPipeline
ModuleNotFoundError: No module named 'diffusers'
```

**Comment by zeke** [comment]
@chenxwh should the download script be run from within `cog run bash`?

**Comment by zeke** [comment]
@chenxwh I see you're chipping away at this: https://github.com/replicate/dreambooth/commit/0d4418ae360725f9ae52d3a4a5ab91f714dbd33b -- nice!
